# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 527)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setEnabled(True)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(100, 500))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.frame = QtWidgets.QFrame(self.frame_left_menu)
        self.frame.setGeometry(QtCore.QRect(1, 1, 102, 525))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 525))
        self.frame.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Welcome_Title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Welcome_Title.setFont(font)
        self.Welcome_Title.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 127);\n"
"}")
        self.Welcome_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Welcome_Title.setObjectName("Welcome_Title")
        self.verticalLayout_2.addWidget(self.Welcome_Title)
        self.Name = QtWidgets.QLabel(self.frame)
        self.Name.setStyleSheet("QLabel{\n"
"color : rgb(255, 255, 255)\n"
"}")
        self.Name.setText("")
        self.Name.setObjectName("Name")
        self.verticalLayout_2.addWidget(self.Name)
        self.AccountTypeLabel = QtWidgets.QLabel(self.frame)
        self.AccountTypeLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.AccountTypeLabel.setText("")
        self.AccountTypeLabel.setObjectName("AccountTypeLabel")
        self.verticalLayout_2.addWidget(self.AccountTypeLabel)
        self.LogoutButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LogoutButton.setFont(font)
        self.LogoutButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 0, 17);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.LogoutButton.setObjectName("LogoutButton")
        self.verticalLayout_2.addWidget(self.LogoutButton)
        self.Main_UsersButton = QtWidgets.QPushButton(self.frame)
        self.Main_UsersButton.setMinimumSize(QtCore.QSize(0, 40))
        self.Main_UsersButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Main_UsersButton.setObjectName("Main_UsersButton")
        self.verticalLayout_2.addWidget(self.Main_UsersButton)
        self.Main_TTButton = QtWidgets.QPushButton(self.frame)
        self.Main_TTButton.setMinimumSize(QtCore.QSize(0, 40))
        self.Main_TTButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Main_TTButton.setObjectName("Main_TTButton")
        self.verticalLayout_2.addWidget(self.Main_TTButton)
        self.Main_AttendanceButton = QtWidgets.QPushButton(self.frame)
        self.Main_AttendanceButton.setMinimumSize(QtCore.QSize(0, 40))
        self.Main_AttendanceButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Main_AttendanceButton.setObjectName("Main_AttendanceButton")
        self.verticalLayout_2.addWidget(self.Main_AttendanceButton)
        self.Main_AttendanceStatusButton = QtWidgets.QPushButton(self.frame)
        self.Main_AttendanceStatusButton.setMinimumSize(QtCore.QSize(0, 40))
        self.Main_AttendanceStatusButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Main_AttendanceStatusButton.setObjectName("Main_AttendanceStatusButton")
        self.verticalLayout_2.addWidget(self.Main_AttendanceStatusButton)
        self.Main_StdButton = QtWidgets.QPushButton(self.frame)
        self.Main_StdButton.setMinimumSize(QtCore.QSize(78, 40))
        self.Main_StdButton.setMaximumSize(QtCore.QSize(78, 16777215))
        self.Main_StdButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Main_StdButton.setObjectName("Main_StdButton")
        self.verticalLayout_2.addWidget(self.Main_StdButton)
        self.Main_RecognitionButton = QtWidgets.QPushButton(self.frame)
        self.Main_RecognitionButton.setMinimumSize(QtCore.QSize(0, 40))
        self.Main_RecognitionButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Main_RecognitionButton.setObjectName("Main_RecognitionButton")
        self.verticalLayout_2.addWidget(self.Main_RecognitionButton)
        self.Main_CreditsButton = QtWidgets.QPushButton(self.frame)
        self.Main_CreditsButton.setMinimumSize(QtCore.QSize(0, 40))
        self.Main_CreditsButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Main_CreditsButton.setObjectName("Main_CreditsButton")
        self.verticalLayout_2.addWidget(self.Main_CreditsButton)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.AttendanceStatus = QtWidgets.QWidget()
        self.AttendanceStatus.setObjectName("AttendanceStatus")
        self.TRT_LABEL = QtWidgets.QLabel(self.AttendanceStatus)
        self.TRT_LABEL.setGeometry(QtCore.QRect(10, 20, 131, 20))
        self.TRT_LABEL.setObjectName("TRT_LABEL")
        self.TRS_LABEL = QtWidgets.QLabel(self.AttendanceStatus)
        self.TRS_LABEL.setGeometry(QtCore.QRect(390, 20, 131, 20))
        self.TRS_LABEL.setObjectName("TRS_LABEL")
        self.Teachers = QtWidgets.QComboBox(self.AttendanceStatus)
        self.Teachers.setGeometry(QtCore.QRect(398, 210, 161, 31))
        self.Teachers.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 255, 255);\n"
"    alternate-background-color: rgb(255, 235, 252);\n"
"}")
        self.Teachers.setObjectName("Teachers")
        self.ATS_SearchButton = QtWidgets.QPushButton(self.AttendanceStatus)
        self.ATS_SearchButton.setGeometry(QtCore.QRect(754, 210, 91, 31))
        self.ATS_SearchButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.ATS_SearchButton.setObjectName("ATS_SearchButton")
        self.RollNumber = QtWidgets.QLineEdit(self.AttendanceStatus)
        self.RollNumber.setGeometry(QtCore.QRect(10, 210, 201, 31))
        self.RollNumber.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.RollNumber.setObjectName("RollNumber")
        self.CourseCode = QtWidgets.QLineEdit(self.AttendanceStatus)
        self.CourseCode.setGeometry(QtCore.QRect(220, 210, 171, 31))
        self.CourseCode.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.CourseCode.setObjectName("CourseCode")
        self.CoruseCode_LABEL = QtWidgets.QLabel(self.AttendanceStatus)
        self.CoruseCode_LABEL.setGeometry(QtCore.QRect(220, 180, 131, 21))
        self.CoruseCode_LABEL.setObjectName("CoruseCode_LABEL")
        self.RollNumber_LABEL = QtWidgets.QLabel(self.AttendanceStatus)
        self.RollNumber_LABEL.setGeometry(QtCore.QRect(10, 180, 131, 21))
        self.RollNumber_LABEL.setObjectName("RollNumber_LABEL")
        self.TSA_LABEL = QtWidgets.QLabel(self.AttendanceStatus)
        self.TSA_LABEL.setGeometry(QtCore.QRect(10, 410, 161, 20))
        self.TSA_LABEL.setObjectName("TSA_LABEL")
        self.TotalAttendance = QtWidgets.QLabel(self.AttendanceStatus)
        self.TotalAttendance.setGeometry(QtCore.QRect(10, 440, 201, 51))
        self.TotalAttendance.setStyleSheet("QLabel{\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 4);\n"
"}")
        self.TotalAttendance.setText("")
        self.TotalAttendance.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalAttendance.setObjectName("TotalAttendance")
        self.TotalTeachers = QtWidgets.QLabel(self.AttendanceStatus)
        self.TotalTeachers.setGeometry(QtCore.QRect(10, 50, 201, 111))
        self.TotalTeachers.setStyleSheet("QLabel{\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 4);\n"
"}")
        self.TotalTeachers.setText("")
        self.TotalTeachers.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalTeachers.setObjectName("TotalTeachers")
        self.TotalStudents = QtWidgets.QLabel(self.AttendanceStatus)
        self.TotalStudents.setGeometry(QtCore.QRect(400, 50, 201, 111))
        self.TotalStudents.setStyleSheet("QLabel{\n"
"font: 75 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 4);\n"
"}")
        self.TotalStudents.setText("")
        self.TotalStudents.setAlignment(QtCore.Qt.AlignCenter)
        self.TotalStudents.setObjectName("TotalStudents")
        self.ATS_Table = QtWidgets.QTableWidget(self.AttendanceStatus)
        self.ATS_Table.setGeometry(QtCore.QRect(10, 250, 841, 151))
        self.ATS_Table.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ATS_Table.setObjectName("ATS_Table")
        self.ATS_Table.setColumnCount(13)
        self.ATS_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATS_Table.setHorizontalHeaderItem(12, item)
        self.Department = QtWidgets.QComboBox(self.AttendanceStatus)
        self.Department.setGeometry(QtCore.QRect(570, 210, 171, 31))
        self.Department.setStyleSheet("QComboBox{\n"
"color: rgb(rgb(0, 0, 0));\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.Department.setObjectName("Department")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.Department.addItem("")
        self.stackedWidget.addWidget(self.AttendanceStatus)
        self.std_DB = QtWidgets.QWidget()
        self.std_DB.setObjectName("std_DB")
        self.Student_Title = QtWidgets.QLabel(self.std_DB)
        self.Student_Title.setGeometry(QtCore.QRect(0, 0, 871, 64))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.Student_Title.setFont(font)
        self.Student_Title.setStyleSheet("color: #FFF;")
        self.Student_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Student_Title.setObjectName("Student_Title")
        self.Std_table = QtWidgets.QTableWidget(self.std_DB)
        self.Std_table.setGeometry(QtCore.QRect(0, 240, 871, 261))
        self.Std_table.setStyleSheet("QTableWidget {\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Std_table.setObjectName("Std_table")
        self.Std_table.setColumnCount(10)
        self.Std_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Std_table.setHorizontalHeaderItem(9, item)
        self.RollNumber_Label = QtWidgets.QLabel(self.std_DB)
        self.RollNumber_Label.setGeometry(QtCore.QRect(0, 70, 91, 21))
        self.RollNumber_Label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.RollNumber_Label.setObjectName("RollNumber_Label")
        self.StudentName_Label = QtWidgets.QLabel(self.std_DB)
        self.StudentName_Label.setGeometry(QtCore.QRect(0, 100, 91, 21))
        self.StudentName_Label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.StudentName_Label.setObjectName("StudentName_Label")
        self.Contact_Label = QtWidgets.QLabel(self.std_DB)
        self.Contact_Label.setGeometry(QtCore.QRect(0, 130, 91, 21))
        self.Contact_Label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Contact_Label.setObjectName("Contact_Label")
        self.Email_Label = QtWidgets.QLabel(self.std_DB)
        self.Email_Label.setGeometry(QtCore.QRect(0, 160, 91, 21))
        self.Email_Label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Email_Label.setObjectName("Email_Label")
        self.Department_Label = QtWidgets.QLabel(self.std_DB)
        self.Department_Label.setGeometry(QtCore.QRect(320, 70, 91, 21))
        self.Department_Label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Department_Label.setObjectName("Department_Label")
        self.Batch_Label = QtWidgets.QLabel(self.std_DB)
        self.Batch_Label.setGeometry(QtCore.QRect(320, 100, 91, 21))
        self.Batch_Label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Batch_Label.setObjectName("Batch_Label")
        self.Section_Label = QtWidgets.QLabel(self.std_DB)
        self.Section_Label.setGeometry(QtCore.QRect(320, 130, 91, 21))
        self.Section_Label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Section_Label.setObjectName("Section_Label")
        self.Std_RollNumber = QtWidgets.QLineEdit(self.std_DB)
        self.Std_RollNumber.setGeometry(QtCore.QRect(100, 70, 211, 20))
        self.Std_RollNumber.setStyleSheet("QLineEdit {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_RollNumber.setText("")
        self.Std_RollNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.Std_RollNumber.setObjectName("Std_RollNumber")
        self.Std_Name = QtWidgets.QLineEdit(self.std_DB)
        self.Std_Name.setGeometry(QtCore.QRect(100, 100, 211, 20))
        self.Std_Name.setStyleSheet("QLineEdit {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_Name.setText("")
        self.Std_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Std_Name.setObjectName("Std_Name")
        self.Std_Contact = QtWidgets.QLineEdit(self.std_DB)
        self.Std_Contact.setGeometry(QtCore.QRect(100, 130, 211, 20))
        self.Std_Contact.setStyleSheet("QLineEdit {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_Contact.setText("")
        self.Std_Contact.setAlignment(QtCore.Qt.AlignCenter)
        self.Std_Contact.setObjectName("Std_Contact")
        self.Std_Email = QtWidgets.QLineEdit(self.std_DB)
        self.Std_Email.setGeometry(QtCore.QRect(100, 160, 211, 20))
        self.Std_Email.setStyleSheet("QLineEdit {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_Email.setText("")
        self.Std_Email.setAlignment(QtCore.Qt.AlignCenter)
        self.Std_Email.setObjectName("Std_Email")
        self.Std_Batch = QtWidgets.QLineEdit(self.std_DB)
        self.Std_Batch.setEnabled(True)
        self.Std_Batch.setGeometry(QtCore.QRect(420, 100, 211, 20))
        self.Std_Batch.setStyleSheet("QLineEdit {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_Batch.setText("")
        self.Std_Batch.setAlignment(QtCore.Qt.AlignCenter)
        self.Std_Batch.setPlaceholderText("")
        self.Std_Batch.setClearButtonEnabled(False)
        self.Std_Batch.setObjectName("Std_Batch")
        self.Std_Section = QtWidgets.QLineEdit(self.std_DB)
        self.Std_Section.setGeometry(QtCore.QRect(420, 130, 41, 21))
        self.Std_Section.setStyleSheet("QLineEdit {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_Section.setText("")
        self.Std_Section.setMaxLength(1)
        self.Std_Section.setAlignment(QtCore.Qt.AlignCenter)
        self.Std_Section.setObjectName("Std_Section")
        self.Std_AddButton = QtWidgets.QPushButton(self.std_DB)
        self.Std_AddButton.setGeometry(QtCore.QRect(650, 70, 121, 23))
        self.Std_AddButton.setStyleSheet("QPushButton {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}")
        self.Std_AddButton.setObjectName("Std_AddButton")
        self.Std_UpdateButton = QtWidgets.QPushButton(self.std_DB)
        self.Std_UpdateButton.setGeometry(QtCore.QRect(650, 100, 121, 23))
        self.Std_UpdateButton.setStyleSheet("QPushButton {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}")
        self.Std_UpdateButton.setObjectName("Std_UpdateButton")
        self.Std_DeleteButton = QtWidgets.QPushButton(self.std_DB)
        self.Std_DeleteButton.setGeometry(QtCore.QRect(780, 160, 91, 23))
        self.Std_DeleteButton.setStyleSheet("QPushButton {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}")
        self.Std_DeleteButton.setObjectName("Std_DeleteButton")
        self.Std_DisplayButton = QtWidgets.QPushButton(self.std_DB)
        self.Std_DisplayButton.setGeometry(QtCore.QRect(610, 200, 251, 31))
        self.Std_DisplayButton.setStyleSheet("QPushButton {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}")
        self.Std_DisplayButton.setObjectName("Std_DisplayButton")
        self.Std_ClearButton = QtWidgets.QPushButton(self.std_DB)
        self.Std_ClearButton.setGeometry(QtCore.QRect(650, 130, 121, 23))
        self.Std_ClearButton.setStyleSheet("QPushButton {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}")
        self.Std_ClearButton.setObjectName("Std_ClearButton")
        self.Std_DeleteStudent = QtWidgets.QLineEdit(self.std_DB)
        self.Std_DeleteStudent.setGeometry(QtCore.QRect(650, 160, 121, 21))
        self.Std_DeleteStudent.setStyleSheet("QLineEdit {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_DeleteStudent.setObjectName("Std_DeleteStudent")
        self.Std_DeleteLabel = QtWidgets.QLabel(self.std_DB)
        self.Std_DeleteLabel.setGeometry(QtCore.QRect(480, 160, 161, 21))
        self.Std_DeleteLabel.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Std_DeleteLabel.setObjectName("Std_DeleteLabel")
        self.Std_DepartmentComboBox = QtWidgets.QComboBox(self.std_DB)
        self.Std_DepartmentComboBox.setGeometry(QtCore.QRect(420, 70, 211, 22))
        self.Std_DepartmentComboBox.setStyleSheet("QComboBox{\n"
"color: rgb(rgb(0, 0, 0));\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.Std_DepartmentComboBox.setObjectName("Std_DepartmentComboBox")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_DepartmentComboBox.addItem("")
        self.Std_SearchButton = QtWidgets.QPushButton(self.std_DB)
        self.Std_SearchButton.setGeometry(QtCore.QRect(402, 200, 201, 31))
        self.Std_SearchButton.setStyleSheet("QPushButton {\n"
"    color: rgb(rgb(15, 15, 15));\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}")
        self.Std_SearchButton.setObjectName("Std_SearchButton")
        self.Std_SearchFeild = QtWidgets.QLineEdit(self.std_DB)
        self.Std_SearchFeild.setGeometry(QtCore.QRect(2, 200, 231, 31))
        self.Std_SearchFeild.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.Std_SearchFeild.setObjectName("Std_SearchFeild")
        self.Std_SearchComboBox = QtWidgets.QComboBox(self.std_DB)
        self.Std_SearchComboBox.setGeometry(QtCore.QRect(240, 200, 151, 31))
        self.Std_SearchComboBox.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.Std_SearchComboBox.setObjectName("Std_SearchComboBox")
        self.Std_SearchComboBox.addItem("")
        self.Std_SearchComboBox.addItem("")
        self.Std_SearchComboBox.addItem("")
        self.Std_SearchComboBox.addItem("")
        self.Std_SearchComboBox.addItem("")
        self.checkBox = QtWidgets.QCheckBox(self.std_DB)
        self.checkBox.setGeometry(QtCore.QRect(320, 160, 131, 17))
        self.checkBox.setStyleSheet("QCheckBox{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.CamIp = QtWidgets.QLineEdit(self.std_DB)
        self.CamIp.setGeometry(QtCore.QRect(520, 130, 113, 20))
        self.CamIp.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.CamIp.setObjectName("CamIp")
        self.Section_Label_2 = QtWidgets.QLabel(self.std_DB)
        self.Section_Label_2.setGeometry(QtCore.QRect(470, 130, 41, 21))
        self.Section_Label_2.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"")
        self.Section_Label_2.setObjectName("Section_Label_2")
        self.stackedWidget.addWidget(self.std_DB)
        self.TimeTable = QtWidgets.QWidget()
        self.TimeTable.setObjectName("TimeTable")
        self.TimeTable_Title = QtWidgets.QLabel(self.TimeTable)
        self.TimeTable_Title.setGeometry(QtCore.QRect(0, 0, 871, 64))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.TimeTable_Title.setFont(font)
        self.TimeTable_Title.setStyleSheet("color: #FFF;")
        self.TimeTable_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeTable_Title.setObjectName("TimeTable_Title")
        self.TT_Table = QtWidgets.QTableWidget(self.TimeTable)
        self.TT_Table.setGeometry(QtCore.QRect(0, 240, 871, 231))
        self.TT_Table.setStyleSheet("QTableWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_Table.setObjectName("TT_Table")
        self.TT_Table.setColumnCount(11)
        self.TT_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TT_Table.setHorizontalHeaderItem(10, item)
        self.TT_DayLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_DayLabel.setGeometry(QtCore.QRect(0, 70, 51, 21))
        self.TT_DayLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_DayLabel.setObjectName("TT_DayLabel")
        self.TT_StartLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_StartLabel.setGeometry(QtCore.QRect(0, 100, 61, 21))
        self.TT_StartLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_StartLabel.setObjectName("TT_StartLabel")
        self.TT_EndLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_EndLabel.setGeometry(QtCore.QRect(180, 100, 47, 16))
        self.TT_EndLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_EndLabel.setObjectName("TT_EndLabel")
        self.TT_StartTime = QtWidgets.QTimeEdit(self.TimeTable)
        self.TT_StartTime.setGeometry(QtCore.QRect(60, 100, 111, 22))
        self.TT_StartTime.setStyleSheet("QTimeEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.TT_StartTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 6, 1), QtCore.QTime(15, 0, 0)))
        self.TT_StartTime.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 6, 1), QtCore.QTime(23, 59, 59)))
        self.TT_StartTime.setMaximumTime(QtCore.QTime(23, 59, 59))
        self.TT_StartTime.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.TT_StartTime.setTimeSpec(QtCore.Qt.LocalTime)
        self.TT_StartTime.setTime(QtCore.QTime(15, 0, 0))
        self.TT_StartTime.setObjectName("TT_StartTime")
        self.TT_EndTime = QtWidgets.QTimeEdit(self.TimeTable)
        self.TT_EndTime.setGeometry(QtCore.QRect(240, 100, 91, 22))
        self.TT_EndTime.setStyleSheet("QTimeEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.TT_EndTime.setObjectName("TT_EndTime")
        self.TT_DayComboBox = QtWidgets.QComboBox(self.TimeTable)
        self.TT_DayComboBox.setGeometry(QtCore.QRect(60, 70, 111, 22))
        self.TT_DayComboBox.setStyleSheet("QComboBox{\n"
"color: rgb(rgb(0, 0, 0));\n"
"background-color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.TT_DayComboBox.setObjectName("TT_DayComboBox")
        self.TT_DayComboBox.addItem("")
        self.TT_DayComboBox.addItem("")
        self.TT_DayComboBox.addItem("")
        self.TT_DayComboBox.addItem("")
        self.TT_DayComboBox.addItem("")
        self.TT_DayComboBox.addItem("")
        self.TT_DayComboBox.addItem("")
        self.TT_TeacherLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_TeacherLabel.setGeometry(QtCore.QRect(0, 130, 71, 21))
        self.TT_TeacherLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_TeacherLabel.setObjectName("TT_TeacherLabel")
        self.TT_CourseLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_CourseLabel.setGeometry(QtCore.QRect(0, 160, 71, 21))
        self.TT_CourseLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_CourseLabel.setObjectName("TT_CourseLabel")
        self.TT_CourseCodeLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_CourseCodeLabel.setGeometry(QtCore.QRect(340, 160, 71, 21))
        self.TT_CourseCodeLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_CourseCodeLabel.setObjectName("TT_CourseCodeLabel")
        self.TT_DepartmentLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_DepartmentLabel.setGeometry(QtCore.QRect(340, 70, 71, 21))
        self.TT_DepartmentLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_DepartmentLabel.setObjectName("TT_DepartmentLabel")
        self.TT_BatchLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_BatchLabel.setGeometry(QtCore.QRect(340, 100, 71, 21))
        self.TT_BatchLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_BatchLabel.setObjectName("TT_BatchLabel")
        self.TT_SectionLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_SectionLabel.setGeometry(QtCore.QRect(340, 130, 71, 21))
        self.TT_SectionLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TT_SectionLabel.setObjectName("TT_SectionLabel")
        self.TT_TeacherComboBox = QtWidgets.QComboBox(self.TimeTable)
        self.TT_TeacherComboBox.setGeometry(QtCore.QRect(80, 130, 251, 22))
        self.TT_TeacherComboBox.setStyleSheet("QComboBox{\n"
"color: rgb(rgb(0, 0, 0));\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.TT_TeacherComboBox.setObjectName("TT_TeacherComboBox")
        self.TT_Course = QtWidgets.QLineEdit(self.TimeTable)
        self.TT_Course.setGeometry(QtCore.QRect(80, 160, 251, 21))
        self.TT_Course.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.TT_Course.setObjectName("TT_Course")
        self.TT_DepartmentComboBox = QtWidgets.QComboBox(self.TimeTable)
        self.TT_DepartmentComboBox.setGeometry(QtCore.QRect(420, 70, 251, 22))
        self.TT_DepartmentComboBox.setStyleSheet("QComboBox{\n"
"color: rgb(rgb(0, 0, 0));\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.TT_DepartmentComboBox.setObjectName("TT_DepartmentComboBox")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_DepartmentComboBox.addItem("")
        self.TT_CourseCode = QtWidgets.QLineEdit(self.TimeTable)
        self.TT_CourseCode.setGeometry(QtCore.QRect(420, 160, 131, 21))
        self.TT_CourseCode.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.TT_CourseCode.setObjectName("TT_CourseCode")
        self.TT_AddButton = QtWidgets.QPushButton(self.TimeTable)
        self.TT_AddButton.setGeometry(QtCore.QRect(750, 70, 121, 23))
        self.TT_AddButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_AddButton.setObjectName("TT_AddButton")
        self.TT_DeleteButton = QtWidgets.QPushButton(self.TimeTable)
        self.TT_DeleteButton.setGeometry(QtCore.QRect(750, 130, 121, 23))
        self.TT_DeleteButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_DeleteButton.setObjectName("TT_DeleteButton")
        self.TT_UpdateButton = QtWidgets.QPushButton(self.TimeTable)
        self.TT_UpdateButton.setGeometry(QtCore.QRect(750, 100, 121, 23))
        self.TT_UpdateButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_UpdateButton.setObjectName("TT_UpdateButton")
        self.TT_ClearButton = QtWidgets.QPushButton(self.TimeTable)
        self.TT_ClearButton.setGeometry(QtCore.QRect(750, 160, 121, 23))
        self.TT_ClearButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_ClearButton.setObjectName("TT_ClearButton")
        self.TT_DisplayButton = QtWidgets.QPushButton(self.TimeTable)
        self.TT_DisplayButton.setGeometry(QtCore.QRect(560, 160, 181, 23))
        self.TT_DisplayButton.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_DisplayButton.setObjectName("TT_DisplayButton")
        self.TT_EncodingLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_EncodingLabel.setGeometry(QtCore.QRect(0, 200, 61, 21))
        self.TT_EncodingLabel.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"")
        self.TT_EncodingLabel.setObjectName("TT_EncodingLabel")
        self.TT_SelectButton = QtWidgets.QPushButton(self.TimeTable)
        self.TT_SelectButton.setGeometry(QtCore.QRect(300, 200, 75, 23))
        self.TT_SelectButton.setStyleSheet("QPushButton{\n"
"color: rgb(rgb(0, 0, 0));\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.TT_SelectButton.setObjectName("TT_SelectButton")
        self.TT_Delete = QtWidgets.QLineEdit(self.TimeTable)
        self.TT_Delete.setGeometry(QtCore.QRect(662, 130, 81, 21))
        self.TT_Delete.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.TT_Delete.setObjectName("TT_Delete")
        self.TT_DeleteLabel = QtWidgets.QLabel(self.TimeTable)
        self.TT_DeleteLabel.setGeometry(QtCore.QRect(560, 130, 101, 21))
        self.TT_DeleteLabel.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.TT_DeleteLabel.setObjectName("TT_DeleteLabel")
        self.TT_Batch = QtWidgets.QLineEdit(self.TimeTable)
        self.TT_Batch.setGeometry(QtCore.QRect(420, 100, 131, 21))
        self.TT_Batch.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_Batch.setObjectName("TT_Batch")
        self.TT_Section = QtWidgets.QLineEdit(self.TimeTable)
        self.TT_Section.setGeometry(QtCore.QRect(420, 130, 131, 21))
        self.TT_Section.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_Section.setObjectName("TT_Section")
        self.TT_ClassEnc = QtWidgets.QLineEdit(self.TimeTable)
        self.TT_ClassEnc.setGeometry(QtCore.QRect(70, 200, 221, 21))
        self.TT_ClassEnc.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.TT_ClassEnc.setText("")
        self.TT_ClassEnc.setObjectName("TT_ClassEnc")
        self.stackedWidget.addWidget(self.TimeTable)
        self.Recognition = QtWidgets.QWidget()
        self.Recognition.setObjectName("Recognition")
        self.FRP_Title = QtWidgets.QLabel(self.Recognition)
        self.FRP_Title.setGeometry(QtCore.QRect(0, -10, 881, 64))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.FRP_Title.setFont(font)
        self.FRP_Title.setStyleSheet("color: #FFF;")
        self.FRP_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.FRP_Title.setObjectName("FRP_Title")
        self.TrainingDatasetGroupBox = QtWidgets.QGroupBox(self.Recognition)
        self.TrainingDatasetGroupBox.setGeometry(QtCore.QRect(0, 60, 411, 201))
        self.TrainingDatasetGroupBox.setStyleSheet("QGroupBox{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.TrainingDatasetGroupBox.setObjectName("TrainingDatasetGroupBox")
        self.FRP_TrainButton = QtWidgets.QPushButton(self.TrainingDatasetGroupBox)
        self.FRP_TrainButton.setGeometry(QtCore.QRect(80, 140, 201, 51))
        self.FRP_TrainButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.FRP_TrainButton.setObjectName("FRP_TrainButton")
        self.FRP_SelectTrainButton = QtWidgets.QPushButton(self.TrainingDatasetGroupBox)
        self.FRP_SelectTrainButton.setGeometry(QtCore.QRect(330, 50, 41, 31))
        self.FRP_SelectTrainButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectTrainButton.setObjectName("FRP_SelectTrainButton")
        self.FRP_SelectTrain = QtWidgets.QLineEdit(self.TrainingDatasetGroupBox)
        self.FRP_SelectTrain.setGeometry(QtCore.QRect(90, 50, 231, 31))
        self.FRP_SelectTrain.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectTrain.setText("")
        self.FRP_SelectTrain.setObjectName("FRP_SelectTrain")
        self.FRP_TrainDirectoryLabel = QtWidgets.QLabel(self.TrainingDatasetGroupBox)
        self.FRP_TrainDirectoryLabel.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.FRP_TrainDirectoryLabel.setObjectName("FRP_TrainDirectoryLabel")
        self.FRP_TrainSaveAsLabel = QtWidgets.QLabel(self.TrainingDatasetGroupBox)
        self.FRP_TrainSaveAsLabel.setGeometry(QtCore.QRect(40, 95, 61, 21))
        self.FRP_TrainSaveAsLabel.setObjectName("FRP_TrainSaveAsLabel")
        self.FRP_SaveAs = QtWidgets.QLineEdit(self.TrainingDatasetGroupBox)
        self.FRP_SaveAs.setGeometry(QtCore.QRect(90, 90, 231, 31))
        self.FRP_SaveAs.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SaveAs.setObjectName("FRP_SaveAs")
        self.ImageRecognitionGroupBox = QtWidgets.QGroupBox(self.Recognition)
        self.ImageRecognitionGroupBox.setGeometry(QtCore.QRect(460, 60, 401, 201))
        self.ImageRecognitionGroupBox.setStyleSheet("QGroupBox{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.ImageRecognitionGroupBox.setObjectName("ImageRecognitionGroupBox")
        self.FRP_SelectImageButton = QtWidgets.QPushButton(self.ImageRecognitionGroupBox)
        self.FRP_SelectImageButton.setGeometry(QtCore.QRect(330, 25, 41, 31))
        self.FRP_SelectImageButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectImageButton.setObjectName("FRP_SelectImageButton")
        self.FRP_SelectImage = QtWidgets.QLineEdit(self.ImageRecognitionGroupBox)
        self.FRP_SelectImage.setGeometry(QtCore.QRect(100, 25, 221, 31))
        self.FRP_SelectImage.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectImage.setObjectName("FRP_SelectImage")
        self.FRP_ImageFileLabel = QtWidgets.QLabel(self.ImageRecognitionGroupBox)
        self.FRP_ImageFileLabel.setGeometry(QtCore.QRect(10, 25, 81, 31))
        self.FRP_ImageFileLabel.setObjectName("FRP_ImageFileLabel")
        self.FRP_ImageEncodingLabel = QtWidgets.QLabel(self.ImageRecognitionGroupBox)
        self.FRP_ImageEncodingLabel.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.FRP_ImageEncodingLabel.setObjectName("FRP_ImageEncodingLabel")
        self.FRP_SelectImageEncoding = QtWidgets.QLineEdit(self.ImageRecognitionGroupBox)
        self.FRP_SelectImageEncoding.setGeometry(QtCore.QRect(100, 65, 221, 31))
        self.FRP_SelectImageEncoding.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectImageEncoding.setObjectName("FRP_SelectImageEncoding")
        self.FRP_ImageButton = QtWidgets.QPushButton(self.ImageRecognitionGroupBox)
        self.FRP_ImageButton.setGeometry(QtCore.QRect(110, 140, 201, 51))
        self.FRP_ImageButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.FRP_ImageButton.setObjectName("FRP_ImageButton")
        self.FRP_SelectImageEncodingButton = QtWidgets.QPushButton(self.ImageRecognitionGroupBox)
        self.FRP_SelectImageEncodingButton.setGeometry(QtCore.QRect(330, 65, 41, 31))
        self.FRP_SelectImageEncodingButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectImageEncodingButton.setObjectName("FRP_SelectImageEncodingButton")
        self.FRP_ImgResultLabel = QtWidgets.QLabel(self.ImageRecognitionGroupBox)
        self.FRP_ImgResultLabel.setGeometry(QtCore.QRect(10, 105, 81, 21))
        self.FRP_ImgResultLabel.setObjectName("FRP_ImgResultLabel")
        self.FRP_ImgResult = QtWidgets.QLineEdit(self.ImageRecognitionGroupBox)
        self.FRP_ImgResult.setGeometry(QtCore.QRect(100, 100, 221, 31))
        self.FRP_ImgResult.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_ImgResult.setObjectName("FRP_ImgResult")
        self.VideoRecognitionGroupBox = QtWidgets.QGroupBox(self.Recognition)
        self.VideoRecognitionGroupBox.setGeometry(QtCore.QRect(0, 290, 411, 211))
        self.VideoRecognitionGroupBox.setStyleSheet("QGroupBox{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.VideoRecognitionGroupBox.setObjectName("VideoRecognitionGroupBox")
        self.FRP_SelectVideoButton = QtWidgets.QPushButton(self.VideoRecognitionGroupBox)
        self.FRP_SelectVideoButton.setGeometry(QtCore.QRect(340, 20, 41, 31))
        self.FRP_SelectVideoButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectVideoButton.setObjectName("FRP_SelectVideoButton")
        self.FRP_SelectVideo = QtWidgets.QLineEdit(self.VideoRecognitionGroupBox)
        self.FRP_SelectVideo.setGeometry(QtCore.QRect(90, 20, 231, 31))
        self.FRP_SelectVideo.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectVideo.setObjectName("FRP_SelectVideo")
        self.FRP_VideoDirectoryLabel = QtWidgets.QLabel(self.VideoRecognitionGroupBox)
        self.FRP_VideoDirectoryLabel.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.FRP_VideoDirectoryLabel.setObjectName("FRP_VideoDirectoryLabel")
        self.FRP_VideoEncodingLabel = QtWidgets.QLabel(self.VideoRecognitionGroupBox)
        self.FRP_VideoEncodingLabel.setGeometry(QtCore.QRect(10, 60, 81, 31))
        self.FRP_VideoEncodingLabel.setObjectName("FRP_VideoEncodingLabel")
        self.FRP_SelectVideoEncoding = QtWidgets.QLineEdit(self.VideoRecognitionGroupBox)
        self.FRP_SelectVideoEncoding.setGeometry(QtCore.QRect(90, 60, 231, 31))
        self.FRP_SelectVideoEncoding.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectVideoEncoding.setObjectName("FRP_SelectVideoEncoding")
        self.FRP_VideoButton = QtWidgets.QPushButton(self.VideoRecognitionGroupBox)
        self.FRP_VideoButton.setGeometry(QtCore.QRect(90, 140, 201, 51))
        self.FRP_VideoButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.FRP_VideoButton.setObjectName("FRP_VideoButton")
        self.FRP_SelectVideoEncodingButton = QtWidgets.QPushButton(self.VideoRecognitionGroupBox)
        self.FRP_SelectVideoEncodingButton.setGeometry(QtCore.QRect(340, 60, 41, 31))
        self.FRP_SelectVideoEncodingButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_SelectVideoEncodingButton.setObjectName("FRP_SelectVideoEncodingButton")
        self.FRP_VidResultLabel = QtWidgets.QLabel(self.VideoRecognitionGroupBox)
        self.FRP_VidResultLabel.setGeometry(QtCore.QRect(10, 105, 81, 21))
        self.FRP_VidResultLabel.setObjectName("FRP_VidResultLabel")
        self.FRP_VidResult = QtWidgets.QLineEdit(self.VideoRecognitionGroupBox)
        self.FRP_VidResult.setGeometry(QtCore.QRect(90, 100, 231, 31))
        self.FRP_VidResult.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_VidResult.setObjectName("FRP_VidResult")
        self.lineEdit = QtWidgets.QLineEdit(self.Recognition)
        self.lineEdit.setGeometry(QtCore.QRect(560, 390, 251, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.LiveStreamGroupBox = QtWidgets.QGroupBox(self.Recognition)
        self.LiveStreamGroupBox.setGeometry(QtCore.QRect(450, 290, 401, 201))
        self.LiveStreamGroupBox.setStyleSheet("QGroupBox{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.LiveStreamGroupBox.setObjectName("LiveStreamGroupBox")
        self.FRP_CamIP = QtWidgets.QLineEdit(self.LiveStreamGroupBox)
        self.FRP_CamIP.setGeometry(QtCore.QRect(100, 50, 271, 31))
        self.FRP_CamIP.setStyleSheet("QLineEdit{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.FRP_CamIP.setText("")
        self.FRP_CamIP.setObjectName("FRP_CamIP")
        self.FRP_CamIPLABEL = QtWidgets.QLabel(self.LiveStreamGroupBox)
        self.FRP_CamIPLABEL.setGeometry(QtCore.QRect(50, 50, 41, 31))
        self.FRP_CamIPLABEL.setObjectName("FRP_CamIPLABEL")
        self.FRP_LiveButton = QtWidgets.QPushButton(self.LiveStreamGroupBox)
        self.FRP_LiveButton.setGeometry(QtCore.QRect(40, 100, 331, 51))
        self.FRP_LiveButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.FRP_LiveButton.setObjectName("FRP_LiveButton")
        self.stackedWidget.addWidget(self.Recognition)
        self.AttendanceRecord = QtWidgets.QWidget()
        self.AttendanceRecord.setObjectName("AttendanceRecord")
        self.ATR_Title = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_Title.setGeometry(QtCore.QRect(0, 0, 871, 64))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.ATR_Title.setFont(font)
        self.ATR_Title.setStyleSheet("color: #FFF;")
        self.ATR_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.ATR_Title.setObjectName("ATR_Title")
        self.ATR_Table = QtWidgets.QTableWidget(self.AttendanceRecord)
        self.ATR_Table.setGeometry(QtCore.QRect(0, 220, 871, 281))
        self.ATR_Table.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_Table.setObjectName("ATR_Table")
        self.ATR_Table.setColumnCount(13)
        self.ATR_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.ATR_Table.setHorizontalHeaderItem(12, item)
        self.ATR_Date = QtWidgets.QDateEdit(self.AttendanceRecord)
        self.ATR_Date.setGeometry(QtCore.QRect(80, 70, 110, 22))
        self.ATR_Date.setStyleSheet("QDateEdit{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_Date.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.ATR_Date.setCalendarPopup(True)
        self.ATR_Date.setObjectName("ATR_Date")
        self.ATR_DateLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_DateLabel.setGeometry(QtCore.QRect(0, 70, 71, 21))
        self.ATR_DateLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_DateLabel.setObjectName("ATR_DateLabel")
        self.ATR_TeacherLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_TeacherLabel.setGeometry(QtCore.QRect(200, 70, 71, 21))
        self.ATR_TeacherLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_TeacherLabel.setObjectName("ATR_TeacherLabel")
        self.ATR_TeacherComboBox = QtWidgets.QComboBox(self.AttendanceRecord)
        self.ATR_TeacherComboBox.setGeometry(QtCore.QRect(280, 70, 191, 22))
        self.ATR_TeacherComboBox.setAutoFillBackground(False)
        self.ATR_TeacherComboBox.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ATR_TeacherComboBox.setObjectName("ATR_TeacherComboBox")
        self.ATR_DepartmentLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_DepartmentLabel.setGeometry(QtCore.QRect(480, 70, 71, 21))
        self.ATR_DepartmentLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_DepartmentLabel.setObjectName("ATR_DepartmentLabel")
        self.ATR_BatchLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_BatchLabel.setGeometry(QtCore.QRect(760, 70, 41, 21))
        self.ATR_BatchLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_BatchLabel.setObjectName("ATR_BatchLabel")
        self.ATR_SectionLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_SectionLabel.setGeometry(QtCore.QRect(0, 100, 71, 21))
        self.ATR_SectionLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_SectionLabel.setObjectName("ATR_SectionLabel")
        self.ATR_RollNumbeLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_RollNumbeLabel.setGeometry(QtCore.QRect(130, 100, 71, 21))
        self.ATR_RollNumbeLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_RollNumbeLabel.setObjectName("ATR_RollNumbeLabel")
        self.ATR_StudentNameLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_StudentNameLabel.setGeometry(QtCore.QRect(370, 100, 71, 21))
        self.ATR_StudentNameLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_StudentNameLabel.setObjectName("ATR_StudentNameLabel")
        self.ATR_RollNumber = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_RollNumber.setGeometry(QtCore.QRect(210, 100, 151, 21))
        self.ATR_RollNumber.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_RollNumber.setObjectName("ATR_RollNumber")
        self.ATR_StudentName = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_StudentName.setGeometry(QtCore.QRect(450, 100, 151, 21))
        self.ATR_StudentName.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_StudentName.setObjectName("ATR_StudentName")
        self.ATR_CourseCodeLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_CourseCodeLabel.setGeometry(QtCore.QRect(610, 100, 71, 21))
        self.ATR_CourseCodeLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_CourseCodeLabel.setObjectName("ATR_CourseCodeLabel")
        self.ATR_CourseCode = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_CourseCode.setGeometry(QtCore.QRect(690, 100, 151, 21))
        self.ATR_CourseCode.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_CourseCode.setObjectName("ATR_CourseCode")
        self.ATR_SearchButton = QtWidgets.QPushButton(self.AttendanceRecord)
        self.ATR_SearchButton.setGeometry(QtCore.QRect(400, 180, 111, 31))
        self.ATR_SearchButton.setStyleSheet("QPushButton{\n"
" \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.ATR_SearchButton.setObjectName("ATR_SearchButton")
        self.ATR_DisplayButton = QtWidgets.QPushButton(self.AttendanceRecord)
        self.ATR_DisplayButton.setGeometry(QtCore.QRect(750, 130, 111, 31))
        self.ATR_DisplayButton.setStyleSheet("QPushButton{\n"
" \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.ATR_DisplayButton.setObjectName("ATR_DisplayButton")
        self.ATR_DepartmentComboBox = QtWidgets.QComboBox(self.AttendanceRecord)
        self.ATR_DepartmentComboBox.setGeometry(QtCore.QRect(560, 70, 191, 22))
        self.ATR_DepartmentComboBox.setStyleSheet("QComboBox{\n"
"color: rgb(rgb(0, 0, 0));\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.ATR_DepartmentComboBox.setObjectName("ATR_DepartmentComboBox")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_DepartmentComboBox.addItem("")
        self.ATR_Section = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_Section.setGeometry(QtCore.QRect(80, 100, 41, 21))
        self.ATR_Section.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_Section.setObjectName("ATR_Section")
        self.ATR_Batch = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_Batch.setGeometry(QtCore.QRect(810, 70, 61, 21))
        self.ATR_Batch.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_Batch.setObjectName("ATR_Batch")
        self.ATR_AddButton = QtWidgets.QPushButton(self.AttendanceRecord)
        self.ATR_AddButton.setGeometry(QtCore.QRect(530, 130, 101, 31))
        self.ATR_AddButton.setStyleSheet("QPushButton{\n"
" \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.ATR_AddButton.setObjectName("ATR_AddButton")
        self.ATR_UpdateButton = QtWidgets.QPushButton(self.AttendanceRecord)
        self.ATR_UpdateButton.setGeometry(QtCore.QRect(640, 130, 101, 31))
        self.ATR_UpdateButton.setStyleSheet("QPushButton{\n"
" \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.ATR_UpdateButton.setObjectName("ATR_UpdateButton")
        self.ATR_DeleteButton = QtWidgets.QPushButton(self.AttendanceRecord)
        self.ATR_DeleteButton.setGeometry(QtCore.QRect(760, 170, 111, 41))
        self.ATR_DeleteButton.setStyleSheet("QPushButton{\n"
" \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.ATR_DeleteButton.setObjectName("ATR_DeleteButton")
        self.ATR_SearchComboBox = QtWidgets.QComboBox(self.AttendanceRecord)
        self.ATR_SearchComboBox.setGeometry(QtCore.QRect(238, 180, 151, 31))
        self.ATR_SearchComboBox.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.ATR_SearchComboBox.setObjectName("ATR_SearchComboBox")
        self.ATR_SearchComboBox.addItem("")
        self.ATR_SearchComboBox.addItem("")
        self.ATR_SearchComboBox.addItem("")
        self.ATR_SearchComboBox.addItem("")
        self.ATR_SearchComboBox.addItem("")
        self.ATR_SearchFeild = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_SearchFeild.setGeometry(QtCore.QRect(0, 180, 231, 31))
        self.ATR_SearchFeild.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_SearchFeild.setObjectName("ATR_SearchFeild")
        self.ATR_TimeFirstSessionLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_TimeFirstSessionLabel.setGeometry(QtCore.QRect(0, 130, 91, 31))
        self.ATR_TimeFirstSessionLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_TimeFirstSessionLabel.setObjectName("ATR_TimeFirstSessionLabel")
        self.ATR_TimeSecSessionLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_TimeSecSessionLabel.setGeometry(QtCore.QRect(250, 130, 111, 31))
        self.ATR_TimeSecSessionLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_TimeSecSessionLabel.setObjectName("ATR_TimeSecSessionLabel")
        self.ATR_TimeSecondSession = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_TimeSecondSession.setGeometry(QtCore.QRect(370, 130, 151, 31))
        self.ATR_TimeSecondSession.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_TimeSecondSession.setObjectName("ATR_TimeSecondSession")
        self.ATR_TimeFirstSession = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_TimeFirstSession.setGeometry(QtCore.QRect(90, 130, 151, 31))
        self.ATR_TimeFirstSession.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_TimeFirstSession.setObjectName("ATR_TimeFirstSession")
        self.ATR_DeleteUpdateLabel = QtWidgets.QLabel(self.AttendanceRecord)
        self.ATR_DeleteUpdateLabel.setGeometry(QtCore.QRect(520, 180, 151, 21))
        self.ATR_DeleteUpdateLabel.setStyleSheet("QLabel{\n"
"rgb(255, 255, 255)\n"
"}")
        self.ATR_DeleteUpdateLabel.setObjectName("ATR_DeleteUpdateLabel")
        self.ATR_DeleteUpdate = QtWidgets.QLineEdit(self.AttendanceRecord)
        self.ATR_DeleteUpdate.setGeometry(QtCore.QRect(680, 180, 71, 31))
        self.ATR_DeleteUpdate.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.ATR_DeleteUpdate.setObjectName("ATR_DeleteUpdate")
        self.stackedWidget.addWidget(self.AttendanceRecord)
        self.Credits = QtWidgets.QWidget()
        self.Credits.setObjectName("Credits")
        self.Credits_Title = QtWidgets.QLabel(self.Credits)
        self.Credits_Title.setEnabled(True)
        self.Credits_Title.setGeometry(QtCore.QRect(0, 0, 871, 511))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Credits_Title.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(11)
        self.Credits_Title.setFont(font)
        self.Credits_Title.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Credits_Title.setStyleSheet("color: #FFF;")
        self.Credits_Title.setTextFormat(QtCore.Qt.PlainText)
        self.Credits_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Credits_Title.setWordWrap(False)
        self.Credits_Title.setObjectName("Credits_Title")
        self.stackedWidget.addWidget(self.Credits)
        self.Users = QtWidgets.QWidget()
        self.Users.setObjectName("Users")
        self.Users_NameLabel = QtWidgets.QLabel(self.Users)
        self.Users_NameLabel.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.Users_NameLabel.setObjectName("Users_NameLabel")
        self.Users_PasswordLabel = QtWidgets.QLabel(self.Users)
        self.Users_PasswordLabel.setGeometry(QtCore.QRect(10, 115, 71, 21))
        self.Users_PasswordLabel.setObjectName("Users_PasswordLabel")
        self.Users_Title = QtWidgets.QLabel(self.Users)
        self.Users_Title.setGeometry(QtCore.QRect(0, 0, 871, 64))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.Users_Title.setFont(font)
        self.Users_Title.setStyleSheet("color: #FFF;")
        self.Users_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Users_Title.setObjectName("Users_Title")
        self.Users_Username = QtWidgets.QLineEdit(self.Users)
        self.Users_Username.setGeometry(QtCore.QRect(90, 80, 181, 21))
        self.Users_Username.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.Users_Username.setObjectName("Users_Username")
        self.Users_Password = QtWidgets.QLineEdit(self.Users)
        self.Users_Password.setGeometry(QtCore.QRect(90, 119, 181, 21))
        self.Users_Password.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.Users_Password.setObjectName("Users_Password")
        self.Users_AccountLabel = QtWidgets.QLabel(self.Users)
        self.Users_AccountLabel.setGeometry(QtCore.QRect(280, 80, 91, 21))
        self.Users_AccountLabel.setObjectName("Users_AccountLabel")
        self.Users_AccountComboBox = QtWidgets.QComboBox(self.Users)
        self.Users_AccountComboBox.setGeometry(QtCore.QRect(380, 80, 101, 22))
        self.Users_AccountComboBox.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.Users_AccountComboBox.setObjectName("Users_AccountComboBox")
        self.Users_AccountComboBox.addItem("")
        self.Users_AccountComboBox.addItem("")
        self.Users_CreateButton = QtWidgets.QPushButton(self.Users)
        self.Users_CreateButton.setGeometry(QtCore.QRect(510, 70, 191, 31))
        self.Users_CreateButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.Users_CreateButton.setObjectName("Users_CreateButton")
        self.Users_UpdateButton = QtWidgets.QPushButton(self.Users)
        self.Users_UpdateButton.setGeometry(QtCore.QRect(560, 110, 141, 31))
        self.Users_UpdateButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.Users_UpdateButton.setObjectName("Users_UpdateButton")
        self.Users_DeleteButton = QtWidgets.QPushButton(self.Users)
        self.Users_DeleteButton.setGeometry(QtCore.QRect(710, 110, 161, 31))
        self.Users_DeleteButton.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.Users_DeleteButton.setObjectName("Users_DeleteButton")
        self.Users_DeleteLabel = QtWidgets.QLabel(self.Users)
        self.Users_DeleteLabel.setGeometry(QtCore.QRect(710, 60, 101, 41))
        self.Users_DeleteLabel.setObjectName("Users_DeleteLabel")
        self.Users_Delete = QtWidgets.QLineEdit(self.Users)
        self.Users_Delete.setGeometry(QtCore.QRect(820, 70, 51, 31))
        self.Users_Delete.setStyleSheet("QLineEdit{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Users_Delete.setObjectName("Users_Delete")
        self.Users_FullNameLabel = QtWidgets.QLabel(self.Users)
        self.Users_FullNameLabel.setGeometry(QtCore.QRect(280, 120, 61, 21))
        self.Users_FullNameLabel.setObjectName("Users_FullNameLabel")
        self.Users_FullName = QtWidgets.QLineEdit(self.Users)
        self.Users_FullName.setGeometry(QtCore.QRect(340, 120, 211, 21))
        self.Users_FullName.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.Users_FullName.setObjectName("Users_FullName")
        self.Users_Table = QtWidgets.QTableWidget(self.Users)
        self.Users_Table.setGeometry(QtCore.QRect(150, 190, 501, 311))
        self.Users_Table.setStyleSheet("QTableWidget {\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.Users_Table.setObjectName("Users_Table")
        self.Users_Table.setColumnCount(5)
        self.Users_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Users_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Users_Table.setHorizontalHeaderItem(4, item)
        self.stackedWidget.addWidget(self.Users)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.frame_pages.raise_()
        self.frame_left_menu.raise_()
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition Based Attendance System Control Panel"))
        self.Welcome_Title.setText(_translate("MainWindow", "WELCOME"))
        self.LogoutButton.setText(_translate("MainWindow", "LOGOUT"))
        self.Main_UsersButton.setText(_translate("MainWindow", "Users"))
        self.Main_TTButton.setText(_translate("MainWindow", "Time Table"))
        self.Main_AttendanceButton.setText(_translate("MainWindow", "Attendance \n"
" Record"))
        self.Main_AttendanceStatusButton.setText(_translate("MainWindow", "Attendance \n"
" Status"))
        self.Main_StdButton.setText(_translate("MainWindow", "Student\n"
" Database"))
        self.Main_RecognitionButton.setText(_translate("MainWindow", "Recognition"))
        self.Main_CreditsButton.setText(_translate("MainWindow", "Credits"))
        self.TRT_LABEL.setText(_translate("MainWindow", "Total Registered Teachers"))
        self.TRS_LABEL.setText(_translate("MainWindow", "Total Registered Students"))
        self.ATS_SearchButton.setText(_translate("MainWindow", "Search"))
        self.CoruseCode_LABEL.setText(_translate("MainWindow", "Course Code:"))
        self.RollNumber_LABEL.setText(_translate("MainWindow", "Roll Number"))
        self.TSA_LABEL.setText(_translate("MainWindow", "Tota Student Attendance"))
        item = self.ATS_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.ATS_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.ATS_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Day"))
        item = self.ATS_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Roll Number"))
        item = self.ATS_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "1st Session"))
        item = self.ATS_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "2nd Session"))
        item = self.ATS_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.ATS_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Teacher"))
        item = self.ATS_Table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Course Name"))
        item = self.ATS_Table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Course Code"))
        item = self.ATS_Table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Department"))
        item = self.ATS_Table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Batch"))
        item = self.ATS_Table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Section"))
        self.Department.setItemText(0, _translate("MainWindow", "Electronics Engineering"))
        self.Department.setItemText(1, _translate("MainWindow", "Electrical Engineering"))
        self.Department.setItemText(2, _translate("MainWindow", "Computer Engineering"))
        self.Department.setItemText(3, _translate("MainWindow", "Software Engineering"))
        self.Department.setItemText(4, _translate("MainWindow", "Civil Engineering"))
        self.Department.setItemText(5, _translate("MainWindow", "Bio-Medical Engineering"))
        self.Department.setItemText(6, _translate("MainWindow", "Bio-Informatics"))
        self.Department.setItemText(7, _translate("MainWindow", "Telecommunication Engineering"))
        self.Department.setItemText(8, _translate("MainWindow", "BS Computer Science"))
        self.Department.setItemText(9, _translate("MainWindow", "BS Information Technology"))
        self.Student_Title.setText(_translate("MainWindow", "STUDENT DATABASE"))
        item = self.Std_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.Std_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Roll Number"))
        item = self.Std_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Student Name"))
        item = self.Std_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contact"))
        item = self.Std_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.Std_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Department"))
        item = self.Std_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Batch"))
        item = self.Std_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Section"))
        item = self.Std_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Directory"))
        self.RollNumber_Label.setText(_translate("MainWindow", "Roll Number:"))
        self.StudentName_Label.setText(_translate("MainWindow", "Student Name:"))
        self.Contact_Label.setText(_translate("MainWindow", "Contact:"))
        self.Email_Label.setText(_translate("MainWindow", "Email:"))
        self.Department_Label.setText(_translate("MainWindow", "Department:"))
        self.Batch_Label.setText(_translate("MainWindow", "Batch:"))
        self.Section_Label.setText(_translate("MainWindow", "Section:"))
        self.Std_AddButton.setText(_translate("MainWindow", "Add"))
        self.Std_UpdateButton.setText(_translate("MainWindow", "Update"))
        self.Std_DeleteButton.setText(_translate("MainWindow", "Delete"))
        self.Std_DisplayButton.setText(_translate("MainWindow", "Display All Information"))
        self.Std_ClearButton.setText(_translate("MainWindow", "Clear"))
        self.Std_DeleteLabel.setText(_translate("MainWindow", "ENTER ID TO DELETE / UPDATE:"))
        self.Std_DepartmentComboBox.setItemText(0, _translate("MainWindow", "Electronics Engineering"))
        self.Std_DepartmentComboBox.setItemText(1, _translate("MainWindow", "Electrical Engineering"))
        self.Std_DepartmentComboBox.setItemText(2, _translate("MainWindow", "Computer Engineering"))
        self.Std_DepartmentComboBox.setItemText(3, _translate("MainWindow", "Software Engineering"))
        self.Std_DepartmentComboBox.setItemText(4, _translate("MainWindow", "Civil Engineering"))
        self.Std_DepartmentComboBox.setItemText(5, _translate("MainWindow", "Bio-Medical Engineering"))
        self.Std_DepartmentComboBox.setItemText(6, _translate("MainWindow", "Bio-Informatics"))
        self.Std_DepartmentComboBox.setItemText(7, _translate("MainWindow", "Telecommunication Engineering"))
        self.Std_DepartmentComboBox.setItemText(8, _translate("MainWindow", "BS Computer Science"))
        self.Std_DepartmentComboBox.setItemText(9, _translate("MainWindow", "BS Information Technology"))
        self.Std_SearchButton.setText(_translate("MainWindow", "Search"))
        self.Std_SearchComboBox.setItemText(0, _translate("MainWindow", "Student Name"))
        self.Std_SearchComboBox.setItemText(1, _translate("MainWindow", "Roll Number"))
        self.Std_SearchComboBox.setItemText(2, _translate("MainWindow", "Email"))
        self.Std_SearchComboBox.setItemText(3, _translate("MainWindow", "Department"))
        self.Std_SearchComboBox.setItemText(4, _translate("MainWindow", "Batch"))
        self.checkBox.setText(_translate("MainWindow", "Add Pictures Manually"))
        self.Section_Label_2.setText(_translate("MainWindow", "CAM IP:"))
        self.TimeTable_Title.setText(_translate("MainWindow", "TIME TABLE"))
        item = self.TT_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.TT_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Day"))
        item = self.TT_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start Time"))
        item = self.TT_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End Time"))
        item = self.TT_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Teacher"))
        item = self.TT_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Course"))
        item = self.TT_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Course Code"))
        item = self.TT_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Department"))
        item = self.TT_Table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Batch"))
        item = self.TT_Table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Section"))
        item = self.TT_Table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Encodings"))
        self.TT_DayLabel.setText(_translate("MainWindow", "Day:"))
        self.TT_StartLabel.setText(_translate("MainWindow", "Start Time:"))
        self.TT_EndLabel.setText(_translate("MainWindow", "End Time"))
        self.TT_DayComboBox.setItemText(0, _translate("MainWindow", "Sunday"))
        self.TT_DayComboBox.setItemText(1, _translate("MainWindow", "Monday"))
        self.TT_DayComboBox.setItemText(2, _translate("MainWindow", "Tuesday"))
        self.TT_DayComboBox.setItemText(3, _translate("MainWindow", "Wednesday"))
        self.TT_DayComboBox.setItemText(4, _translate("MainWindow", "Thursday"))
        self.TT_DayComboBox.setItemText(5, _translate("MainWindow", "Friday"))
        self.TT_DayComboBox.setItemText(6, _translate("MainWindow", "Saturday"))
        self.TT_TeacherLabel.setText(_translate("MainWindow", "Teacher Name:"))
        self.TT_CourseLabel.setText(_translate("MainWindow", "Course:"))
        self.TT_CourseCodeLabel.setText(_translate("MainWindow", "Course Code:"))
        self.TT_DepartmentLabel.setText(_translate("MainWindow", "Department:"))
        self.TT_BatchLabel.setText(_translate("MainWindow", "Batch:"))
        self.TT_SectionLabel.setText(_translate("MainWindow", "Section:"))
        self.TT_DepartmentComboBox.setItemText(0, _translate("MainWindow", "Electronics Engineering"))
        self.TT_DepartmentComboBox.setItemText(1, _translate("MainWindow", "Electrical Engineering"))
        self.TT_DepartmentComboBox.setItemText(2, _translate("MainWindow", "Computer Engineering"))
        self.TT_DepartmentComboBox.setItemText(3, _translate("MainWindow", "Software Engineering"))
        self.TT_DepartmentComboBox.setItemText(4, _translate("MainWindow", "Civil Engineering"))
        self.TT_DepartmentComboBox.setItemText(5, _translate("MainWindow", "Bio-Medical Engineering"))
        self.TT_DepartmentComboBox.setItemText(6, _translate("MainWindow", "Bio-Informatics"))
        self.TT_DepartmentComboBox.setItemText(7, _translate("MainWindow", "Telecommunication Engineering"))
        self.TT_DepartmentComboBox.setItemText(8, _translate("MainWindow", "BS Computer Science"))
        self.TT_DepartmentComboBox.setItemText(9, _translate("MainWindow", "BS Information Technology"))
        self.TT_AddButton.setText(_translate("MainWindow", "Add"))
        self.TT_DeleteButton.setText(_translate("MainWindow", "Delete"))
        self.TT_UpdateButton.setText(_translate("MainWindow", "Update"))
        self.TT_ClearButton.setText(_translate("MainWindow", "Clear"))
        self.TT_DisplayButton.setText(_translate("MainWindow", "Display All"))
        self.TT_EncodingLabel.setText(_translate("MainWindow", "Encodings:"))
        self.TT_SelectButton.setText(_translate("MainWindow", "Select"))
        self.TT_DeleteLabel.setText(_translate("MainWindow", "Enter ID to DELETE:"))
        self.FRP_Title.setText(_translate("MainWindow", "FACE RECOGNITION PANEL"))
        self.TrainingDatasetGroupBox.setTitle(_translate("MainWindow", "Training Dataset"))
        self.FRP_TrainButton.setText(_translate("MainWindow", "Training Dataset"))
        self.FRP_SelectTrainButton.setText(_translate("MainWindow", "...."))
        self.FRP_TrainDirectoryLabel.setText(_translate("MainWindow", "Select Directory:"))
        self.FRP_TrainSaveAsLabel.setText(_translate("MainWindow", "Save As:"))
        self.ImageRecognitionGroupBox.setTitle(_translate("MainWindow", "Image Recognition"))
        self.FRP_SelectImageButton.setText(_translate("MainWindow", "...."))
        self.FRP_ImageFileLabel.setText(_translate("MainWindow", "Select File:"))
        self.FRP_ImageEncodingLabel.setText(_translate("MainWindow", "Select Encoding:"))
        self.FRP_ImageButton.setText(_translate("MainWindow", "Image Recognition"))
        self.FRP_SelectImageEncodingButton.setText(_translate("MainWindow", "...."))
        self.FRP_ImgResultLabel.setText(_translate("MainWindow", "Save Result As:"))
        self.VideoRecognitionGroupBox.setTitle(_translate("MainWindow", "Video Recognition"))
        self.FRP_SelectVideoButton.setText(_translate("MainWindow", "...."))
        self.FRP_VideoDirectoryLabel.setText(_translate("MainWindow", "Select File :"))
        self.FRP_VideoEncodingLabel.setText(_translate("MainWindow", "Select Encoding: "))
        self.FRP_VideoButton.setText(_translate("MainWindow", "Video Recognition"))
        self.FRP_SelectVideoEncodingButton.setText(_translate("MainWindow", "...."))
        self.FRP_VidResultLabel.setText(_translate("MainWindow", "Save Result As:"))
        self.LiveStreamGroupBox.setTitle(_translate("MainWindow", "LIVE STREAMING"))
        self.FRP_CamIPLABEL.setText(_translate("MainWindow", "Enter IP:"))
        self.FRP_LiveButton.setText(_translate("MainWindow", "LIVE STREAM"))
        self.ATR_Title.setText(_translate("MainWindow", "ATTENDANCE RECORDS"))
        item = self.ATR_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.ATR_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.ATR_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Day"))
        item = self.ATR_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Roll Number"))
        item = self.ATR_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "1st Session"))
        item = self.ATR_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "2nd Session"))
        item = self.ATR_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.ATR_Table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Teacher"))
        item = self.ATR_Table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Course Name"))
        item = self.ATR_Table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Course Code"))
        item = self.ATR_Table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Department"))
        item = self.ATR_Table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Batch"))
        item = self.ATR_Table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Section"))
        self.ATR_Date.setDisplayFormat(_translate("MainWindow", "M/d/yy"))
        self.ATR_DateLabel.setText(_translate("MainWindow", "Date:"))
        self.ATR_TeacherLabel.setText(_translate("MainWindow", "Teacher:"))
        self.ATR_DepartmentLabel.setText(_translate("MainWindow", "Department:"))
        self.ATR_BatchLabel.setText(_translate("MainWindow", "Batch:"))
        self.ATR_SectionLabel.setText(_translate("MainWindow", "Section:"))
        self.ATR_RollNumbeLabel.setText(_translate("MainWindow", "Roll Number:"))
        self.ATR_StudentNameLabel.setText(_translate("MainWindow", "Student Name:"))
        self.ATR_CourseCodeLabel.setText(_translate("MainWindow", "Course Code:"))
        self.ATR_SearchButton.setText(_translate("MainWindow", "Search"))
        self.ATR_DisplayButton.setText(_translate("MainWindow", "Display ALL"))
        self.ATR_DepartmentComboBox.setItemText(0, _translate("MainWindow", "Electronics Engineering"))
        self.ATR_DepartmentComboBox.setItemText(1, _translate("MainWindow", "Electrical Engineering"))
        self.ATR_DepartmentComboBox.setItemText(2, _translate("MainWindow", "Computer Engineering"))
        self.ATR_DepartmentComboBox.setItemText(3, _translate("MainWindow", "Software Engineering"))
        self.ATR_DepartmentComboBox.setItemText(4, _translate("MainWindow", "Civil Engineering"))
        self.ATR_DepartmentComboBox.setItemText(5, _translate("MainWindow", "Bio-Medical Engineering"))
        self.ATR_DepartmentComboBox.setItemText(6, _translate("MainWindow", "Bio-Informatics"))
        self.ATR_DepartmentComboBox.setItemText(7, _translate("MainWindow", "Telecommunication Engineering"))
        self.ATR_DepartmentComboBox.setItemText(8, _translate("MainWindow", "BS Computer Science"))
        self.ATR_DepartmentComboBox.setItemText(9, _translate("MainWindow", "BS Information Technology"))
        self.ATR_AddButton.setText(_translate("MainWindow", "Add "))
        self.ATR_UpdateButton.setText(_translate("MainWindow", "Update"))
        self.ATR_DeleteButton.setText(_translate("MainWindow", "Delete"))
        self.ATR_SearchComboBox.setItemText(0, _translate("MainWindow", "Student Name"))
        self.ATR_SearchComboBox.setItemText(1, _translate("MainWindow", "Date"))
        self.ATR_SearchComboBox.setItemText(2, _translate("MainWindow", "Course Code"))
        self.ATR_SearchComboBox.setItemText(3, _translate("MainWindow", "Teacher Name"))
        self.ATR_SearchComboBox.setItemText(4, _translate("MainWindow", "Roll Number"))
        self.ATR_TimeFirstSessionLabel.setText(_translate("MainWindow", "Time First Session:"))
        self.ATR_TimeSecSessionLabel.setText(_translate("MainWindow", "Time Second Session:"))
        self.ATR_DeleteUpdateLabel.setText(_translate("MainWindow", "Enter ID To DELETE / UPDATE:"))
        self.Credits_Title.setText(_translate("MainWindow", "PROJECT DEVELOPED BY\n"
"\n"
"2017-EE-044 SYED RAJAL ALI NAQVI\n"
"2017-EE-002 MUHAMMAD SUFYAN SHAIKH\n"
"2017-EE-050 HAMZA MISBAH\n"
"2017-EE-004 WAQAS SHAHID\n"
"\n"
"\n"
"Under Supervision of\n"
"DR.LUBNA FARHI & ENGR. HIRA ABBASI\n"
"\n"
"\n"
"DEPARTMENT OF ELECTRONICS ENGINEERING\n"
"SIR SYED UNIVERSITY OF ENGINEERING & TECHNOLOGY"))
        self.Users_NameLabel.setText(_translate("MainWindow", "Usename:"))
        self.Users_PasswordLabel.setText(_translate("MainWindow", "password"))
        self.Users_Title.setText(_translate("MainWindow", "USERS CONTROL PANEL"))
        self.Users_AccountLabel.setText(_translate("MainWindow", "Account Type :"))
        self.Users_AccountComboBox.setItemText(0, _translate("MainWindow", "Administrator"))
        self.Users_AccountComboBox.setItemText(1, _translate("MainWindow", "Teacher"))
        self.Users_CreateButton.setText(_translate("MainWindow", "Create Account"))
        self.Users_UpdateButton.setText(_translate("MainWindow", "Update "))
        self.Users_DeleteButton.setText(_translate("MainWindow", "Delete Account"))
        self.Users_DeleteLabel.setText(_translate("MainWindow", "Enter ID to Delete:"))
        self.Users_FullNameLabel.setText(_translate("MainWindow", "Full Name:"))
        item = self.Users_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.Users_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.Users_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.Users_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Account Type"))
        item = self.Users_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Full Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
